# Generated by Django 4.2.5 on 2023-10-09 23:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sample_type', models.CharField(max_length=200)),
                ('normal_value', models.CharField(max_length=200)),
                ('referance_range', models.CharField(max_length=200)),
                ('proccessing_time', models.FloatField()),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('describtion', models.TextField()),
            ],
            options={
                'db_table': 'LabTest',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('order_status', models.CharField(default='Pending', max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor')),
                ('labtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.labtest')),
            ],
            options={
                'db_table': 'LabTestOrder',
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='LabTestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('payment_date', models.DateField(auto_now=True)),
                ('labtest_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.labtestorder')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.patient')),
            ],
            options={
                'db_table': 'LabTestPayment',
                'ordering': ['payment_date'],
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='orders',
            field=models.ManyToManyField(through='tests.LabTestOrder', to='users.appointment'),
        ),
    ]
