# Generated by Django 4.2.5 on 2023-10-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=50)),
                ('systolic_pressure', models.CharField(max_length=50)),
                ('diastolic_pressure', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('body_weight', models.CharField(max_length=50)),
                ('heart_rate', models.CharField(max_length=50)),
                ('respiratory_rate', models.CharField(max_length=50)),
                ('oxygen_saturation', models.CharField(max_length=50)),
                ('date_vital_taken', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nurse')),
            ],
        ),
    ]
