# Generated by Django 4.2.5 on 2023-10-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_vitalregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalregistration',
            options={'ordering': ['-appointment']},
        ),
        migrations.AlterModelTable(
            name='vitalregistration',
            table='VitalRegistration',
        ),
    ]
