# Generated by Django 4.2.5 on 2023-10-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tests', '0004_labtestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_reason', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment')),
            ],
            options={
                'db_table': 'PatientPaymentHistory',
                'ordering': ['payment_date'],
            },
        ),
    ]
