# Generated by Django 4.2.5 on 2023-10-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tests', '0006_alter_patientpaymenthistory_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sample_taken', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='patients_QRcode')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appointment')),
            ],
        ),
    ]
